### ISSUE TITLE
One exclusive appointment

### ISSUE THREAD

**Issue by irvingsl** [Rogger794/react-appointment-picker#3]
Could be an option, like if we set the maxReservableAppointments to 0, that only one appoitment is acceptable, when we click on another apointment, it automaticallys remove the first one.
I was trying to made that change, but I'm still too newbie in JS.

Thanks!

**Comment by Rogger794** [comment]
Hi irvingsl, maxReservableAppointments represents how many appointments can be selected. I put the deselection like mandatory because I thought that people will run a query for deselect that especific periods of time, so someone else could select an appointment in that periods, also people can select more appointment if they need. The way of selecting and remove the first one should have two transactions in the same function (one for delete the periods selected and one for create the selections in the new appointment periods). I base this way in some movie theaters apps from my country.
I hope you could use this package, if you have some other doubt, I would answer you as soon as possible.

**Comment by Rogger794** [comment]
Hi @irvingsl,
I already add a new feature that can help you.
I hope you can check it.
